<h1 style="position: absolute;width: 220px;height: 46px;left: 290px;top: 310px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 15px;line-height: 47px;text-align: center;/*text-transform: uppercase;*/color: #FFFFFF;">Wardrobe, white.</h1>
    <h1 style="position: absolute;width: 220px;height: 46px;left: 300px;top: 180px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">DESC</h1>
    <h1 style="position: absolute;width: 220px;height: 46px;left: 600px;top: 180px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">Price</h1>
    <h1 style="position: absolute;width: 220px;height: 46px;left: 750px;top: 180px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">amount</h1>
    <div class="dropdown"><button class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="false" type="button" style="position: absolute;/*color: white;*/width: 40px;height: 40px;left: 840px;top: 200px;"></button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">1</a><a class="dropdown-item" role="presentation" href="#">2</a><a class="dropdown-item" role="presentation" href="#">3</a></div>
    </div><button class="btn" type="button" style="font-family: roboto;font-size: 20px;position: absolute;width: 150px;height: 46px;left: 930px;top: 400px;background-color: green;color: white;">CHECKOUT</button><button class="btn btn-warning" type="button"
        style="font-family: roboto;font-size: 20px;position: absolute;width: 150px;height: 46px;left: 100px;top: 400px;">SHOP MORE</button>
    <h1 style="position: absolute;width: 220px;height: 46px;left: 900px;top: 180px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">Total</h1>
    <h1 class="text-monospace text-left" style="font-family: Roboto;font-style: normal;font-weight: bold;font-size: 40px;line-height: 47px;text-align: center;text-transform: uppercase;position: absolute;width: 220px;height: 46px;left: 55px;top: 100px;">CART</h1>
    <h1 style="position: absolute;width: 220px;height: 46px;left: 65px;top: 180px;font-family: Roboto;font-style: normal;/*font-weight: bold;*/font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">item</h1>
    <h1 class="text-uppercase" style="position: absolute;width: 500px;height: 100px;left: 150px;top: 270px;font-family: Roboto;font-style: normal;font-weight: bold;font-size: 20px;line-height: 47px;text-align: center;text-transform: uppercase;color: #FFFFFF;">home no-door wardrobe</h1>
    <h1 class="text-capitalize" style="position: absolute;width: 500px;height: 100px;left: 460px;top: 270px;font-family: Roboto;font-style: normal;font-weight: bold;font-size: 20px;line-height: 47px;text-align: center;/*text-transform: uppercase;*/color: #FFFFFF;">Rp. 3.600.000</h1>
    <h1 class="text-capitalize" style="position: absolute;width: 500px;height: 100px;left: 760px;top: 270px;font-family: Roboto;font-style: normal;font-weight: bold;font-size: 20px;line-height: 47px;text-align: center;/*text-transform: uppercase;*/color: #FFFFFF;">Rp. 3.600.000</h1><img src="assets/img/1%201.png" style="position: absolute;width: 150px;height: 200px;left: 100px;top: 200px;">